### ISSUE TITLE
Meteor code must always run within a Fiber.

### ISSUE THREAD

**Issue by sircharleswatson** [benstr/moneybot#29]
@pcorey After your recent merge with master, the SyncedCron for getting history data is broken :(

```
W20151028-08:27:44.648(-5)? (STDERR) /Users/Charles/Development/Meteor/Projects/moneybot/.meteor/local/build/programs/server/packages/meteor.js:974
W20151028-08:27:44.649(-5)? (STDERR)     throw new Error("Meteor code must always run within a Fiber. " +
W20151028-08:27:44.649(-5)? (STDERR)           ^
W20151028-08:27:44.662(-5)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20151028-08:27:44.662(-5)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20151028-08:27:44.663(-5)? (STDERR)     at Object.Meteor.bindEnvironment (packages/meteor/dynamics_nodejs.js:85:1)
W20151028-08:27:44.663(-5)? (STDERR)     at Object.call (packages/meteor/helpers.js:117:1)
W20151028-08:27:44.663(-5)? (STDERR)     at Object.HTTP.get (packages/http/httpcall_common.js:50:1)
W20151028-08:27:44.663(-5)? (STDERR)     at Object.OANDA.get (marketData/server/oanda.js:21:15)
W20151028-08:27:44.663(-5)? (STDERR)     at Object.OANDA.getCandles (marketData/server/oanda.js:31:16)
W20151028-08:27:44.663(-5)? (STDERR)     at marketData/server/getHistoryData.js:49:28
W20151028-08:27:44.663(-5)? (STDERR)     at complete (/Users/Charles/.meteor/packages/stevezhu_lodash/.3.10.1.1534zxc++os+web.browser+web.cordova/npm/node_modules/lodash/index.js:7697:25)
W20151028-08:27:44.664(-5)? (STDERR)     at [object Object].maxDelayed (/Users/Charles/.meteor/packages/stevezhu_lodash/.3.10.1.1534zxc++os+web.browser+web.cordova/npm/node_modules/lodash/index.js:7714:9)
W20151028-08:27:44.664(-5)? (STDERR)     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

**Comment by pcorey** [comment]
Oof. That's really weird. I wasn't seeing that when I was running it, but that makes sense. I'll get a fix in soon-ish.
